### ISSUE TITLE
recovry image

### ISSUE THREAD

**Issue by excalber** [ChonDoit/ofox_devon#2]
hello am a bit new to this.
i cant find  the recovery.img all i find is the folder named recovery should i just paste the whole folder in the adb directory?
sorry if this seems stupid

**Comment by ChonDoit** [comment]
> hello am a bit new to this. i cant find the recovery.img all i find is the folder named recovery should i just paste the whole folder in the adb directory? sorry if this seems stupid

There is releases section 😑
https://github.com/ChonDoit/ofox_devon/releases
